[project]
name = "koda-workspace"
version = "26.6.11"
requires-python = ">=3.9"
dependencies = [
    "camoufox>=0.4.11",
    "httpx>=0.28.1",
]

[tool.pdm]
resolution-locks = true
distribution = false

[tool.pdm.workspace]
members = [
    "packages/*",
    "apps/*"
]

[tool.bumpver]
current_version = "26.6.11"
version_pattern = "YY.MM.INC0"
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"',
]
"packages/koda/pyproject.toml" = [
    'version = "{version}"',
]
"packages/koda/src/koda/__init__.py" = [
    '__version__ = "{version}"',
]

[dependency-groups]
dev = [
    "ruff>=0.15.17",
    "mypy",
    "mkinit>=1.2.0",
]
